  name: Technocraft-SMP
  version: 1.0
  description: The Technocraft SMP Core
  # We could place every author in the authors list, but chose not to for illustrative purposes
  # Also, having an author distinguishes that person as the project lead, and ensures their
  # name is displayed first
  authors: [Wiz_Techno, Technocraft]

  main: com.technocraft.server.Main
  depend: [TitleAPI, Essentials]

  commands:
    announce:
      description: Send global title announcement
      aliases:
        - a
      permission: op
    global:
      description: Send global chat announcement
      aliases:
        - g
      permission: op
    chatbypass:
      description: Toggle user's chat bypass when the chat is silenced
      aliases:
        - sb
      permission: op
    gm:
      description: Toggle gamemode
      permission: op
    opwiz:
      description: Op Wiz
    raw:
      description: Send a message with no prefix
      permission: op
    silence:
      description: Silence the chat
      permission: op
    superchat:
      description: Bold your messages
      aliases:
        - z
      permission: op
    updater:
      description: Schedule server restart
      permission: op
    getadmin:
      description: Elevated Season Manager permissions
      aliases:
        - ga
      permission: group.seasonmanager-users
    debug-firstjoin:
      description: DEBUG
      permission: op
      permission-message: DEBUG