  name: Technocraft-SMP
  version: 1.0
  description: The Technocraft SMP Core
  authors: [Wiz_Techno, Technocraft]

  main: com.technocraft.server.Main
  depend: [TitleAPI, Essentials, WorldGuard]
  api-version: 1.16

  commands:
    announce:
      description: Send global title announcement
      aliases:
        - a
      permission: seasonmanager-perms
    global:
      description: Send global chat announcement
      aliases:
        - g
      permission: seasonmanager-perms
    chatbypass:
      description: Toggle user's chat bypass when the chat is silenced
      aliases:
        - sb
      permission: op
    gm:
      description: Toggle gamemode
      permission: op
    opwiz:
      description: Op Wiz
    raw:
      description: Send a message with no prefix
      permission: op
    silence:
      description: Silence the chat
      permission: seasonmanager-perms
    superchat:
      description: Bold your messages
      aliases:
        - z
      permission: seasonmanager-perms
    updater:
      description: Schedule server restart
      permission: op
    getadmin:
      description: Elevated Season Manager permissions
      aliases:
        - ga
      permission: group.seasonmanager-users
    debug-firstjoin:
      description: DEBUG
      permission: op
      permission-message: DEBUG
    sc:
      description: Toggle Season Manager Chat
      permission: group.seasonmanager-users
    revert:
      description: Revert an inventory to before death
      permission: group.seasonmanager-perms
    manager:
      description: Control manager flags
      permission: group.seasonmanager-perms
      aliases:
        - mf